tfe_admin_homepage:
    path:     /
    defaults: { _controller: TfeAdminBundle:Default:index }

tfe_admin_statistique:
    path:     /statistique
    defaults: { _controller: TfeAdminBundle:Default:statistiques }

tfe_admin_user_list:
    path:     /list_users
    defaults: { _controller: TfeAdminBundle:Users:index }

tfe_admin_user_profil:
    path : /profil/{id}
    defaults: { _controller: TfeAdminBundle:Users:profil }

tfe_admin_user_account_descact:
    path : /desactiver/{id}
    defaults: { _controller: TfeAdminBundle:Users:desactivationCompte }

tfe_admin_user_account_activation:
    path : /activer/{id}
    defaults: { _controller: TfeAdminBundle:Users:activationCompte }